name: Build and deploy frontend

on:
  push:
    branches:
      - "master"
    paths:
      - "frontend/**"
          
jobs:
  build-and-deploy:

    runs-on: ubuntu-latest

    steps:
    - name: Check out repo
      uses: actions/checkout@v1

    - name: Set up Node.js version
      uses: actions/setup-node@v1
      with:
        node-version: '12'

    - name: Build app
      run: |
        cd frontend
        npm install
        npm run build
    # npm run test
    
    - name: 'Deploy to Azure Web App'
      uses: azure/webapps-deploy@v1
      with: 
        app-name: 'frontend-demo-123456789'
        publish-profile: ${{ secrets.FRONTEND_PUBLISH_PROFILE }}
        package: frontend/dist/
